name: build and deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: 18
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: load env
        run: echo ${{ secrets.env }} > "$(pwd)/.env"
      
      - name: install dependencies
        run: npm install

      - name: pull db schema
        run: npm run pre:build

      - name: build deploy to aws lambda
        run: node ./node_modules/serverless/bin/serverless.js deploy -s prod --verbose